Update for UnrealEngine's wrong file path
PlayCover/PlayTools pull request #174
Opened 2024-12-07 05:01 UTC by Ryu-ga

The file name ue4commandline.txt has been changed to uecommandline.txt in UE5.

Some applications mistakenly use both Library\Users and Documents\Users paths multiple times within a single path, more often than I expected.
To address this, I ensure that PlayTools retrieves the string from the last needle of the incorrect path.

Issue: https://github.com/PlayCover/PlayCover/issues/1755

2024-12-07 08:30 UTC, XuYicong approved these changes

2024-12-07 14:24 UTC, viatearz commented
Have you submitted the latest code?
This code writes the username to the beginning of `UE_PATTERN`, then `//Users/` is missing
``` cpp
static char UE_PATTERN[1024] = "//Users/";
getlogin_r(UE_PATTERN, sizeof(UE_PATTERN) - 8);
```

2024-12-07 14:28 UTC, Ryu-ga commented
> Have you submitted the latest code? This code writes the username to the beginning of `UE_PATTERN`, then `//Users/` is missing
> 
> ```c++
> static char UE_PATTERN[1024] = "//Users/";
> getlogin_r(UE_PATTERN, sizeof(UE_PATTERN) - 8);
> ```

Really, I'm a trash generator..

2024-12-07 14:48 UTC, viatearz commented
Sorry, I can't test it, `getlogin_r` still returns `root` to me.
Have you ever print the result of `getlogin_r`?

2024-12-07 14:52 UTC, Ryu-ga commented
> Sorry, I can't test it, `getlogin_r` still returns `root` to me. Have you ever print the result of `getlogin_r`?

Yes I tested it in both PlayTools and pure C program.

2024-12-20 00:01 UTC, TheMoonThatRises requested changes

2024-12-20 00:01 UTC, TheMoonThatRises commented on PlayTools/PlayLoader.m
> +    getlogin_r(UE_PATTERN + 8, sizeof(UE_PATTERN) - 8);
What does this function do in the code (seems unused)?

2024-12-20 00:01 UTC, TheMoonThatRises commented on PlayTools/PlayLoader.m
> +    char const* p = filename;
Can you rename this variable so it is more descriptive of its purpose?

2024-12-20 00:01 UTC, TheMoonThatRises commented on PlayTools/PlayLoader.m
> +    if (ue_status == 0) {
Will `ue_status` never equal `0` on initialization?

2024-12-26 00:07 UTC, Ryu-ga commented on PlayTools/PlayLoader.m
> +    getlogin_r(UE_PATTERN + 8, sizeof(UE_PATTERN) - 8);
The prefix `//Users` can be insufficient, so I added the username to the prefix path `UE_PATTERN`.

2024-12-26 00:11 UTC, Ryu-ga commented on PlayTools/PlayLoader.m
> +    char const* p = filename;
I will rename the variable `UE_PATTERN` to `USER_HOME` and add a comment for it.

2025-01-28 05:44 UTC, XuYicong commented on PlayTools/PlayLoader.m
> +    char const* p = filename;
Isn't the whole purpose of this assignment to shorten the variable name lol? I think it's fine cause `p` is used within a limited scope and this assignment itself tells us what it is.

2025-01-28 06:25 UTC, TheMoonThatRises approved these changes

2025-01-28 10:31 UTC, merged