fix: Add missing setting data to fix wrong behavior
PlayCover/PlayTools pull request #23
Opened 2022-08-29 17:01 UTC by KhoraLee

I made pr but have two questions.

1. Does adaptive resolution should work only with games? If not we should make resolution's default value 0 for non-game app.
2. Does enabling mouse mapping is intended when mouse mapping is disabled in settings but user press opt key?

2022-09-03 14:10 UTC, IsaacMarovitz requested changes

2022-09-03 14:10 UTC, IsaacMarovitz commented on PlayTools/Controls/PlayInput.swift
> +        if settings.isGame && settings.mouseMapping {
We will be phasing out `isGame` better to just remove it entirely.

2022-09-07 03:15 UTC, IsaacMarovitz commented
Please resolve the conflicts so I can base #31 on this PR

2022-09-07 03:18 UTC, Depal1 approved these changes

2022-09-07 03:27 UTC, KhoraLee commented
@IsaacMarovitz Rebased.

2022-09-07 03:29 UTC, Depal1 approved these changes

2022-09-07 03:29 UTC, merged