TOF fix
PlayCover/PlayTools pull request #55
Opened 2022-12-08 23:13 UTC by iVoider

Don't forget to add libboringssl.tbd and libcoretls_cfhelpers.tbd

2022-12-09 07:39 UTC, PencilNavigator commented
“StolenFromMe” LOL

2022-12-09 16:18 UTC, IsaacMarovitz commented
@iVoider you need to document the full process of defining `CS_OPS_STATUS` and `CS_OPS_IDENTITY`. Also please describe what you mean by `Don't forget to add libboringssl.tbd and libcoretls_cfhelpers.tbd`

2022-12-10 02:24 UTC, TheMoonThatRises commented
I think for `libboringssl.tbd` and `libcoretls_cfhelpers.tbd` you need to add it to frameworks and libraries in PlayTool's target general settings. As for `CS_OPS_STATUS` and `CS_OPS_IDENTITY`, I could only find references to `CS_OPS_STATUS` https://opensource.apple.com/source/xnu/xnu-2782.1.97/bsd/sys/codesign.h referencing codesigning.

2022-12-10 20:45 UTC, IsaacMarovitz commented
@iVoider I can't get this to work. I can see serves, but I can't join them. The same graphical issues as before are present.

2022-12-10 20:48 UTC, IsaacMarovitz requested changes

2022-12-10 20:48 UTC, IsaacMarovitz commented on PlayTools/PlayLoader.m
> +    struct dyld_interpose_tuple {
Fix indentation

2022-12-10 20:48 UTC, IsaacMarovitz commented on PlayTools/PlayLoader.m
> +    if (ops == CS_OPS_STATUS || ops == CS_OPS_IDENTITY) {
You need to include defines for these two variables

2022-12-10 20:48 UTC, IsaacMarovitz commented on PlayTools/PlayLoader.m
> +DYLD_INTERPOSE(my_SSL_set_custom_verify, SSL_set_custom_verify)
Please group all the function implementations and interposes together styled in the same way the ones currently in PlayLoader are styled.

2022-12-10 20:48 UTC, IsaacMarovitz commented on PlayTools/PlayLoader.m
> +#define SSL_VERIFY_NONE 0
Move this define to the top with the other defines

2022-12-10 20:49 UTC, IsaacMarovitz commented
> Don't forget to add libboringssl.tbd and libcoretls_cfhelpers.tbd

If those files are required include the change to the Xcode Project in your PR.

2022-12-22 19:25 UTC, closed without merging