Fix: Default app size now shows normally
PlayCover/PlayTools pull request #77
Opened 2023-01-30 20:40 UTC by JoseMoreville

2023-02-05 05:08 UTC, JoseMoreville commented
Some cleaning at the code is necessary, but tests are welcome

2023-02-06 02:22 UTC, Depal1 commented
Tests of https://github.com/PlayCover/PlayTools/pull/77 (https://github.com/PlayCover/PlayTools/pull/77/commits/2a8b8249d4da01541ed13594cad3b2afd0eaba22) with https://github.com/PlayCover/PlayCover/pull/781 (  https://github.com/PlayCover/PlayCover/pull/781/commits/b0e62b1aaa1be7e638a3653b67133156f5b1b091) on macOS 13.1.

### Angry Birds Space *com.rovio.AngryBirdsSpace*
- App Default
![AB Space App Default](https://user-images.githubusercontent.com/47154119/216867469-1beebdf9-2e24-4c2f-a01a-affc671d7f8d.png)
- 1080p 16:9 [Fix windows issues *off*]
![AB Space 1080p off](https://user-images.githubusercontent.com/47154119/216867608-7dc556ef-da97-4636-bbbb-a8ac70c7b360.png)
- 1080p 16:9 [Fix windows issues *on*]
![AB Space 1080p on](https://user-images.githubusercontent.com/47154119/216867796-b6d79d74-5ba4-483e-b916-7071ab91a10a.png)

### Dadish *com.thomasyoung.gooddadish*
- App Default
![Dadish Default](https://user-images.githubusercontent.com/47154119/216868134-1b214d2a-16bf-4916-9c75-b8e09aaae963.png)
- 1080p 16:9 [Fix windows issues *off*]
![Dadish 1080p off](https://user-images.githubusercontent.com/47154119/216868344-62cadae4-83c7-48ba-aa94-48806da72dc3.png)

### Genshin Impact *com.miHoYo.GenshinImpact*
- App Default
![Genshin Default](https://user-images.githubusercontent.com/47154119/216868548-ea892110-eb20-409d-9b55-8dba9ae26bc2.png)

2023-02-06 08:31 UTC, JoseMoreville commented
@Depal1 is it possible to test this?

2023-02-07 03:45 UTC, Depal1 requested changes
All tests where performed on macOS 13.1 with the commits https://github.com/PlayCover/PlayTools/pull/77/commits/fd6dfbd18ac6893950b009a0aaf16ae9cfd700bf and https://github.com/PlayCover/PlayCover/pull/781/commits/e74e6978fa06e725acfd8691b60a1ef485b22e91 of PlayTools and PlayCover respectively.

App default seems to work as intended on macOS 13.1, both in resizable windows and fixed frames.

The regression regarding improper view window position in non-app-default settings, introduced in changes after the 2.0.7 PlayTools tag for macOS 13.1 and previous versions, is still present on Angry Birds Space. It is unbeknownst to me if it is present on 13.2 too.

A similar regression is present on Plague Inc., which can't be displayed correctly with either `Fix window issues` *on* or *off*, showing in both cases as in the following picture (1080p 16:9).

![Plague 1080p 16:9](https://user-images.githubusercontent.com/47154119/217139060-8e571cdd-c891-4725-b054-2adeecc07810.png)

Tests were also made changing the aspect ratio, in order to visually confirm that window settings were indeed being changed on a general basis. Hence, `Fix window issues` might not be working correctly. Further on this hypothesis, Angry Birds Space is showing in the same way when either `Fix window issues` is *on* or *off*, in contraposition to the behaviour in previous tests.

Rather than checking for macOS 13.2 from PlayCover and giving that information to PlayTools, those checks could be done from PlayTools itself using the corresponding check availability attributes both in Swift and Objective-C, using the equivalent iOS 16.3 check for macOS 13.2 since PlayTools is iOS and then converted via Mac Catalyst. https://developer.apple.com/documentation/swift/marking-api-availability-in-objective-c

It is encouraged to test such an approach first. Otherwise, the purpose of splitting PlayCover from PlayTools is partly defeated by making PlayTools strictly dependent from PlayCover, and worthless as a standalone framework unnecessarily. The former instance has the potential to reduce code too.

2023-02-07 03:45 UTC, Depal1 commented on PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m
> +
New trailing whitespace.

2023-02-07 03:45 UTC, Depal1 commented on PlayTools/PlayScreen.swift
> +        if macOSVersion >= 13.19000 {
```suggestion
        if #available(iOS 16.3, *) {
```

2023-02-07 03:45 UTC, Depal1 commented on PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m
> +    if ([[PlaySettings shared] macOSVersion] >= 13.19000) {
```suggestion
    if(@available(iOS 16.3, *)) {
```
This is the corresponding way to check availability in Objective C.

2023-02-08 18:55 UTC, JoseMoreville commented
The toggle Fix window issues is not meant to work in 13.1 just 13.2 and up. sorry that I forgot to add that check for that in Frontend

2023-02-11 21:54 UTC, JoseMoreville commented on PlayTools/PlayScreen.swift
> +        if macOSVersion >= 13.19000 {
This will be added in next PR.

2023-02-11 21:56 UTC, JoseMoreville commented
@Depal1 sorry, the toggle for fix screen issue is not meant to work for 13.1 just 13.2 and up.
I added that toggle for default screen res too as a way to fix apps that are responsive by default like Twitch, LIFX, Paperback or Aidoku.

2023-02-13 23:57 UTC, Depal1 reviewed
It is working correctly both on macOS 13.1 and 13.2. Since the iOS versions checks are working, the remains of the former check are no longer needed.

2023-02-13 23:57 UTC, Depal1 commented on PlayTools/PlaySettings.swift
> +    @objc lazy var macOSVersion = Double(settingsData.macOSVersion)
```suggestion

```

2023-02-13 23:57 UTC, Depal1 commented on PlayTools/PlaySettings.swift
> +    var macOSVersion: Double = 13.2
```suggestion

```

2023-02-15 02:01 UTC, Depal1 approved these changes

2023-02-15 02:02 UTC, merged